---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '150']

  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        entry: poetry run ruff --fix --exit-non-zero-on-fix --force-exclude
        language: python
        require_serial: true
        args: []
        types_or: [python, pyi]
        additional_dependencies: []

  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: poetry run ruff format --force-exclude
        language: python
        require_serial: true
        args: []
        types_or: [python, pyi]
        additional_dependencies: []

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: [-x]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint-docker
